### PR TITLE
Sync tutorial notebooks from mlrun/demos

### PR DESCRIPTION
**Pull request by omesser**
## Why
Remove the duplication of the `getting-started-tutorial` notebooks which exist in 2 slightly different variants here and in https://github.com/mlrun/demos repo

## What
This PR introduces a one-way sync mechanism (pull) between docs-building in this repo and https://github.com/mlrun/demos repo

### Overview
- The tutorial notebooks and assets (static images) were removed from this repo and will only be maintained on https://github.com/mlrun/demos.
- Upon building the docs site - the tutorial assets will be pulled and slightly modified to fit the needs
- This replaces maintaining 2 copies of the tutorial, by maintaining 1 copy (in `mlrun/demos`) and minimal devops-logic here, which is in charge of syncing in the assets

### Details
- Remove docs/tutorial/*ipynb and their images assets. No more dup
- Added `hack/scripts/sync_tutorial_notebooks.py` which is triggered in `make html-docs` and `make html-docs-dockerized` and syncs in the tutorial notebooks and images from `mlrun/demos/getting-started-tutorial` and edits some internal links to align the notebooks to the generated readthedocs. It does so by editing links to the readthedocs site's html pages with local relative links to markdown files, and editing the links to the assets which are synced to a different relative dir under `_static` due to sphynx restriction.
- This script will need to be maintained if new notebooks/assets are added/removed/renamed in mlrun/demos (as well as the `docs/getting-started-tutorial/index.md`, like to say).
- In the `Makefile` there's now a var called `MLRUN_DEMOS_REF` (current default value: `release/v0.6.x-latest`) - which tells the script from which git ref to sync the assets from, and as more releases of `mlrun/demos` are created, this will need to be maintained as well. This will probably need to change when we release new mlrun minor since it instigates/triggers creation of a new release branch in the demos repo.

### CODE REVIEW

**Comment by yaronha** [comment]
@omesser @Hedingber in the `docs` tutorials we have sphinx annotations (for pointing to various docs e.g. `code_to_func`.. or use doc template rendering options) and plan to add more of those, those cannot be used in the demos git repo, so i'm not sure how we can apply this PR w/o loosing it ?

**Comment by omesser** [comment]
@yaronha we've discussed this offline a while ago.
- Those could still be injected in code on the sync script.
- Even though  - the added value on these isn't worth the code duplication / effort imo

**Comment by yaronha** [comment]
@omesser lets take offline we had discussion w PM on how to handle demos & tutorials overlap in future

**Comment by liranbg** [comment]
stale

**Pull request closed without merging**
