### PR TITLE
[Docs] Typo changes

### PR DESCRIPTION
**Pull request by george0st**
Small typo changes ...

### CODE REVIEW

**Comment by jillnogold** [comment]
Hi @george0st
Thanks for your painstaking, and surely time-consuming, review of the updated MLRun documentation!
I noticed that quite a few comments are about commas. There are two basic paradigms for comma usage. I chose one and went through almost all the documentation to standardize it. And, as it turns out, you would standardize it the other way. It’s the old Oxford comma, which I chose to use:

- I love apples, peaches, raspberries, and blueberries. (w/ Oxford)

Vs.

- I love apples, peaches, raspberries and blueberries. (w/o)

Both options are valid. And, in its favor, the Oxford comma makes it possible to join those last two items by omitting the comma:

- I love sandwiches especially cheese, salami, and peanut butter and jam. (Who can eat a peanut butter sandwich without jam?)

Another standard rule for commas is to use them to separate two independent clauses:

- Retrieve logs of a running process, and watch the progress of the execution until it completes.

and not

- Retrieve logs of a running process and watch the progress of the execution until it completes.

The guidelines for writing MLRun documentation are [here](https://github.com/mlrun/mlrun/blob/development/docs/CONTRIBUTING.md). Please use it as the ground rules for any further (and most welcome) suggestions/fixes for the docs. And please let me know if anything isn’t clear. I truly appreciate your contributions.
Thanks so much, Jill

**Comment by george0st** [comment]
@jillnogold, many thanks for clarification, I rollback my invalid changes (my mistake) and I kept only valid parts (I hope). Many thanks for double check. Best regards Jiri

**Comment by Hedingber** [comment]
@george0st note your branch has conflicts

**Comment by george0st** [comment]
@Hedingber, I hope it seems better

**Comment by Hedingber** [comment]
Merged 🎉 
@jillnogold thanks a lot for the detailed review
@george0st thanks a lot for the contribution

**Pull request merged**
