### PR TITLE
[Development] Retain cause exceptions in logs and raised errors

### PR DESCRIPTION
**Pull request by gtopper**
Throughout the code base, we use `str()` to get the error message from an exception. However, doing so disappears the cause (usually one cause, but potentially cause chain), and can result in useless errors such as
```
> 2022-12-19 11:17:07,388 [info] run executed, status=error
runtime error: failed on pre-loading / post-running of the function
```

This PR introduces an `err_to_str` function to extract all error messages in the cause chain so that instead of `job failed`, we'll get `job failed, caused by: the real error`.

### CODE REVIEW

**Review by liranbg — COMMENTED** [review]
While i see the value of showing the error root cause, sometimes it will be confusing for the client. we "wrap" errors in a way the top level shows what is (or should be) important to him to know why thing is failed. what you are doing here is chaining the err (same as Golang does) but that might not be trivial for the end client

Perhaps, we can, instead of creating a long list of `x caused by y, caused by w, ...`, can provide the top level + root cause? wdyt?

**Review by quaark — APPROVED** [review]
Approved and partially agree with @liranbg. Maybe add a param to the method on whether to bring the entire stack or just top and bottom. So the clients will set the param but for any error in the api/runtime we will log the entire stack.
@liranbg wdyt?

**Comment by gtopper** [comment]
I think it does make sense to show the entire chain in most places. I don't think it ever makes sense to show just the top two though, nor just the top and the bottom.

This is a bit theoretical btw, because I've yet to see an actual chain of 3 or more errors.

If you guys prefer, I could limit this change to certain modules. My motivation for this came from the issue in the description, which eminates from `mlrun.runtimes`.

**Comment by liranbg** [comment]
> I think it does make sense to show the entire chain in most places. I don't think it ever makes sense to show just the top two though, nor just the top and the bottom.
> 
> This is a bit theoretical btw, because I've yet to see an actual chain of 3 or more errors.
> 
> If you guys prefer, I could limit this change to certain modules. My motivation for this came from the issue in the description, which eminates from `mlrun.runtimes`.

In most places, we try to make the err concise to avoid reflecting the inner sides, what you are doing here is the other-way around. I understand the need and I think it has great benefits
question is, what do you earn from seeing x amount of errors in between? usually, if you need the stack you'd simply print/format it.
if you need less, you take the last error message.

that being said, having root+top error chained, gives more idea of why it failed rather than what failed. I am a bit on the edge here, perhaps limiting the chain to 2-3 could make it less risky in terms of readably

**Comment by gtopper** [comment]
Whether showing the cause is necessary, as in the example in the description, or unduly exposes internals, would depend on the specific usage. I made this a code-wide change because I thought the default should be to show the causes, but I didn't go in depth to determine where we might not want the causes displayed.

I'm not really for arbitrarily limiting the chain, but I suppose it doesn't really matter when I've never seen more than one cause (might have seen 2 causes in testing actually, not sure).

Come to think of it, in `mlrun.runtimes`, it probably makes sense to log the traceback, not just the error message (even with causes appended). I'll consider making a separate PR for that.

**Comment by liranbg** [comment]
since this pr is wide and will tend to break due to conflicting errors, please DM me when resolve conflict and will merge

**Review by liranbg — APPROVED** [review]

**Pull request merged**
