### PR TITLE
[Docs] Add artifacts to docs references section

### PR DESCRIPTION
**Pull request by assaf758**
[ML-8605](https://iguazio.atlassian.net/browse/ML-8605)

[ML-8605]: https://iguazio.atlassian.net/browse/ML-8605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by alxtkr77** [comment]
We need to make guidelines how to add things to documentation. One way is to use the index.rst, the other is using mlrun/artifacts/__init__.py::__all__ directive. I must say it is confusing

**Comment by assaf758** [comment]
@rokatyy can you chime in on the correct way to do this?

**Comment by rokatyy** [comment]
@assaf758 there were a lot of discussions regarding the best way to do this. For now please follow the way it is done here https://github.com/mlrun/mlrun/blob/046b46e4dba4352045085f3df829e11a609708c0/docs/api/mlrun.common/mlrun.common.schemas to keep the nested structure the same. In the future we will probably move to using autosummary, but for now we do everything manually.

**Review by rokatyy — CHANGES_REQUESTED** [review]
Please move each module to a separate file as in the example above

**Review by alxtkr77 — APPROVED** [review]

**Pull request merged**
