### PR TITLE
[Track] Updated mlflow version

### PR DESCRIPTION
**Pull request by ZeevRispler**
updated mlflow to 2.16 
https://iguazio.atlassian.net/browse/ML-8711

### CODE REVIEW

**Comment by liranbg** [comment]
you will need to update locked-requirements
`make upgrade-mlrun-deps-lock`

**Comment by ZeevRispler** [comment]
I commented in Jira, there is a missmatch with databricks-sdk @liranbg

**Comment by tomerm-iguazio** [comment]
> databricks-sdk

I will take a look

**Comment by tomerm-iguazio** [comment]
This change breaks one of the tests on `TestDatabricksRuntime.test_rerun`, on default handler.
some of the tests already got broken in databricks runtime along 1.8 because it is not running on the CI, and there are not clients using it, so from my side you can change e databricks-sdk to 0.20, and I will open a ticket to fix it....

dbfs as a datastore has not been damaged.
tnx!

**Comment by tomerm-iguazio** [comment]
CI failed due to https://github.com/apache/arrow/issues/43574.
please limit pyarrow to 17:
pyarrow>=10.0, <18 -> pyarrow>=10.0, <17

After you finish to update requirements file, run again @liranbg comment: `make upgrade-mlrun-deps-lock`.

**Review by liranbg — APPROVED** [review]

**Review by liranbg — APPROVED** [review]

**Pull request merged**
