### PR TITLE
Adding GH actions workflow to build images on each commit to development

### PR DESCRIPTION
**Pull request by Hedingber**
**Motivation:**
1. In our upcoming periodic automated system test we will need to be able to get a development version of mlrun, so we actually need to build (and store) images for each commit to development
2. Though our self-hosted Jenkins is working, it will always be less stable than Github-hosted builders, plus, our Jenkins cluster doesn't hold the pressure of building all images concurrently - Github does.
3. Github actions, Github container registry, Github some-other-tool are cool buzzwords, let's use them

**Thoughts and decisions:** 
1. Our images are huge (~60GB together, 2 images are ~20GB each) GH action disk size is 14GB  -> each image will be built separately in a different action - GPU images (the two heavy ones) won't be built for now
2. Where should we put these images, how should we tag them ->
These images are purely for dev purposes, we don't want anyone ever to mistakenly use them, plus we don't want our production registries (dockerhub and quay) to filled up with endless tags, options we had:
(1) put them in a different registry e.g. `ghcr.io/mlrun/mlrun-api` instead of (`mlrun/mlrun-api`)
(2) put them in a different repo e.g. `mlrun-dev/mlrun-api`
(3) append each image name the `-dev` suffix e.g. `mlrun/mlrun-api-dev`
(4) make it clear in the tag e.g. `unstable-<commit-hash>`
Since these images currently only in use for the system tests CI I settled with (1) and (4) - using the same repo and image names will make our life easier in CI.
If at some point we'll decide to add these dev images to our official registries (dockerhub and quay) we will probably need (3) to not dirt our docker repos with endless tags.
To sum up our images will look like `ghcr.io/mlrun/mlrun-api:unstable-dd130ca`
3. Github offers 2 solutions for docker images - GH packages and GH container registry which one to use ->
Although GHCR is currently in public beta, they already have [migrations docs](https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images) from GH packages to GHCR, so going for packages feels like going in the wrong direction.
Also as you can see in 4, GHCR might enable us features packages doesn't have
4. Building our images from scratch takes a lot of time (~40 minutes for the biggest image), we must leverage docker cache ->
GH actions doesn't easily give docker cache, looking on the number of commits can show the hard work it took to get it to work.
This [article](https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei) sums up nicely what are the options with some exceptions:
* The `docker save` `docker load` option has a plug & play ready (GH action)[https://github.com/satackey/action-docker-layer-caching]
* This dude probably used GH packages on his tests (GHCR probably didn't exist) and this is probably why _"GitHub Packages as a cache (BuildKit)"_ approach failed - I succeeded making this to work, and it did look promising but I didn't choose this approach cause:
a. BuildKit is still not production ready
b. I hit this exact same bug - https://stackoverflow.com/questions/62212325/docker-cache-from-with-buildkit-inline-cache-does-not-work-every-second-time which I couldn't find workaround/solution to
So eventually I went with the _"The GitHub Package Registry"_ (just with GHCR) approach

**Implementation notes:**
1. To make this to work 2 secrets need to be set in the GH repo:
* `CR_PAT` (Container registry personal access token) - I currently used PAT of my account, I'm not aware of other way to do it (e.g. some organization access token)
* `CR_USERNAME` - I currently used my username - for most GH action you can use the auto-given `github.ACTOR` and `secrets.GITHUB_TOKEN` but the token is not working with the GHCR, and if I'll use this actor, each time it will be someone else (the person who merge the PR) and we have one PAT
2. In this PR we totally reached the point where the Makefile simplicity doesn't outstand it's lack of code-ability, there are tons of duplications in what I did, and simply trying to condition stuff looks awful, a simple command line util could have been much nicer - I will replace it in some followup PR.

### CODE REVIEW

**Comment by liranbg** [comment]
Great work on milking these features.

You may be able to build the bigger images while cleaning up more diskspace, take a look at the work being done [here](https://github.com/jens-maus/RaspberryMatic/blob/d5044bef3307bc61166377c162569de1a61cf332/.github/workflows/ci.yml#L34-L40)

**Review by quaark — COMMENTED** [review]
Looks awesome!
Only thing is, because we are using `provctl patch` to run the system tests, I think the tags need to have a version number at the beginning, so the tag would have to be `0.5.2-unstable-dd130ca`.
WDYT about this?

**Comment by Hedingber** [comment]
The link @liranbg gave did add a lot of space, the theory claims that GH runs their actions on the Azure machines that have 50GB so with this cleaning script we're able to get more than the documented 14GB.
The GPU images did successfully built with this cleanup, but for some reason the push failed (with wierd timeouts coming from GHCR), we won't need these GPU images in the near future in the CI so for now continuing without them.
@quaark is correct, `provctl patch` require a semver version, so `unstable-<commit-hash>` is not an option.
3 options came up:
1. 0.5.2-<commit-id> - cause maybe if we have the commit id it’s obvious that it’s not the images for official release, plus, by semver, the meaning of - is pre-release so it kinda already gives this “unstable” information
2. 0.5.2-unstable-<commit-id> - to be clear
3. 0.0.0-<commit-id> - this images doesn’t really represent any release in any way, so maybe we should clearly declare that by doing 0.0.0 , for example in the services screen provazio trims anything after the - so in the screen with the above options you’ll see 0.5.2 and nothing tells you it’s not the real release (not that bad, it’s for our uses). Also practically, I’m giving the version when I build those images, so I will have to code some weird way to determine what was the latest release version relevant to my branch/commit (If doing the other two, with this I simply statically always give 0.0.0)
We've decided to go with option 1

**Review by quaark — COMMENTED** [review]
LGTM

**Review by quaark — APPROVED** [review]
LGTM

**Pull request merged**
