### PR TITLE
[Docs] Details on using downloaded data files in air-gapped sites

### PR DESCRIPTION
**Pull request by jillnogold**

### CODE REVIEW

**Comment by EdmondIguazio** [comment]
@adiso75 @jillnogold 
Looks fine to me, but do we want to have this text on all demos? Or just in one place?
If we go with the 2nd option, maybe we need to put it in the docs and not in the demos.
Your thoughts?

**Comment by jillnogold** [comment]
@adiso75 @EdmondIguazio 
I was thinking along those lines, also. Do we need a paragraph about dark sites with other specific details? Or should it be in the mlrun API topic?

**Comment by adiso75** [comment]
@jillnogold @EdmondIguazio  I think it worth adding a note in our demos that if you run it in a dark site you need to do ....
I suggest you'll sync up with @aviaIguazio  on where exactly to change it in each demo.
Also, when you mention "settings" - you should explain where the user can find this settings (e.g. in the UI, there is a setting section where users can add global env variables, this section is under ...)

**Comment by jillnogold** [comment]
@adiso75 @EdmondIguazio
Discussed with Avi, and updated 2 more tutorials

**Comment by EdmondIguazio** [comment]
@jillnogold seems fine to me.
Closing.

**Comment by adiso75** [comment]
@jillnogold  let's hold on with that till the @jasonnIguazio and @EdmondIguazio  meeting tomorrow as we may want to cover more items under the dark site section.
in any case, since this doc is also for mlrun open source.. we need to add a note such as: "when working with Iguazio platform you can go to the platform setting... etc."

**Comment by jillnogold** [comment]
@EdmondIguazio  @adiso75 
How do you set the environmental variables without the UI?
And if you can't, what to do instead?

**Comment by EdmondIguazio** [comment]
@jillnogold @adiso75 
You need to add a code that looks like this:
`import os`
`os.environ["DEBUSSY"] = 1`

**Comment by jillnogold** [comment]
What is DEBUSSY?
More details pls:
In a dark site:,
    1. Download your data file and save it locally.
    2. Enter 
    import os
   os.environ["DEBUSSY"] = 1
where: ....??
    2. Use the same command for the sample data set path, for example: <br>`source_url = mlrun.get_sample_path(\"data/iris/iris_dataset.csv\")`

**Comment by jillnogold** [comment]
Hi @EdmondIguazio 
Please comment on these two scenarios:
**In an air-gapped site using the MLOps platform:**
    1. Download your data file and save it locally.
    2. In the UI, click the settings icon () in the top-right of the header in any page to open the **Settings** dialog.
    3. Click **Environment variables | Create a new environment variable**, and set an environmental variable: SAMPLE_DATA_SOURCE_URL_PREFIX = the relative path to locally-stored data. For example: <br>`/v3io/bigdata/path/...`
    4. Use the same command for the sample data set path, for example: <br>`source_url = mlrun.get_sample_path(\"data/iris/iris_dataset.csv\")`
    
    In an air-gapped site using MLRun:
    1. Download your data file and save it locally.
    2. Run: 
          `import os`
         `os.environ["env_name"] = 1`
    4. Use the same command for the sample data set path, for example: <br>`source_url = mlrun.get_sample_path(\"data/iris/iris_dataset.csv\")`

Thanks!

**Review by EdmondIguazio — APPROVED** [review]
Please just fix the "2." on numbering

**Pull request merged**
