### PR TITLE
[DOC REVIEW] RST: Fix doc-build warnings and restructure the generated reference doc [IG-13721]

### PR DESCRIPTION
**Pull request by Sharon-iguazio**
Initial PR changes — minor doc restructure changes
- Remove the **"General"** page (**docs/api.rst**) and replace the duplicate intro page from this page and at the start of the **"mlrun Package"** page (generated from **mlrun/__init__.,py**) with a single intro in the mlrun package's index page.
- Change the title of the mlrun package page to **"mlrun Modules"** and rename the related **mlrun.rst** source file to **modules.rst**.

@tebeka  @yaronha please both review.
Miki, these are most of the changes that I suggested this morning.
I think it would be better to have a separate reference page for each module, but I don't have time to check how to do this + Yaron needs to confirm first.

This is the **HTML output**:
**Index page**
mlrun_html pr202 index 200312

**Modules page**
mlrun_html pr202 modules 200312

### CODE REVIEW

**Comment by tebeka** [comment]
See #203 as possible improvement.

**Comment by Sharon-iguazio** [comment]
(17.3.20) I integrated the changes from PR #215 to fix to doc-build changes that were done after PR #202 was initially submitted, and I'll close PR #202 - Fix **conf.py** cosmetics for new project module to eliminate the following doc-build warning:
Eliminate the following build warning:
  ```
  mlrun.project module
  ----------------
  <...>\mlrun\docs\mlrun.rst:19: WARNING: Title underline too short.
  ```
- Remove unused file **docs/contents.rst** to eliminate the following docs build error:
  ```
  checking consistency... <...>\mlrun\docs\contents.rst: WARNING: document isn't included in any toctree
  ```

**Comment by Sharon-iguazio** [comment]
**TODO** @yaronha @tebeka we need to also resolve the following **doc-build warnings**:
1. The following warning was introduced when the `project` module was added to the docs build in PR #213 (even though the generated reference includes `module.project`):
  ```
  WARNING: autodoc: failed to import module 'project' from module 'mlrun'; the following exception was raised:
  No module named 'mlrun.project'
  ```
2. `static_path` (used in **conf.py**) doesn't exist:
  ```
  WARNING: html_static_path entry '_static' does not exist
  ```
3.
  ```
  writing additional pages...  searchc:\<...>\mlrun\venv\lib\site-packages\sphinx_rtd_theme\search.html:21: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  ```

**Comment by Sharon-iguazio** [comment]
I'm closing this PR as it's now obsolete in light of newer MLRun doc-infrastructure changes.

**Pull request closed without merging**
