### PR TITLE
[Doc] getting-started-tutorial: NB 2: Step 2, start/end code-markers, and preface docs edits

### PR DESCRIPTION
**Pull request by Sharon-iguazio**
@gilad-shaham @yaronha please review.

### CODE REVIEW

**Comment by yaronha** [comment]
@Sharon-iguazio i prefer to keep as little text vs actual code sections, no need to elaborate too much on some of those things, can point to other doc areas

**Comment by Sharon-iguazio** [comment]
> 
> 
> @Sharon-iguazio i prefer to keep as little text vs actual code sections, no need to elaborate too much on some of those things, can point to other doc areas

@yaronha I expanded the doc mainly in the "Converting the Code to an MLRun Function" section. Before I reduce this text again, which doc page should we link to here for more information? I couldn't find a dedicated doc page referring to the notebook-code to MLRun-function conversion. Should I link to the `mlrun.code_to_function` reference at https://mlrun.readthedocs.io/en/release-v0.6.x-latest/api/mlrun.html#mlrun.code_to_function?

(BTW, when using https://mlrun.readthedocs.io/en/release-v0.6.x-latest/api/mlrun.html#mlrun.code_to_function the page view begins inside the prototype code block, a bit after the start of the function-reference section.)

**Comment by Sharon-iguazio** [comment]
@yaronha @gilad-shaham I pushed some more changes to NB #2 to the PR branch. This completes my doc review for this NB.
Note that in a few places the doc seems to contain obsolete references to code elements and paths that have been changed in recent code updates, so I adjusted the doc to the best of my understanding. See specifically

1. "Running the Exploration Function" in Step 3 — I changed
    ```marldown
    This information is provided as a `table` input artifact that points to the `iris_dataset` output artifact of the `get_data` job that you ran in the previous steps (using the job's `get_data_run` run object &mdash; see [Tutorial 1 Step 2](./01-mlrun-basics.ipynb#gs-tutorial-1-step-create-basic-function).
    ```
    to the following to replace the references to obsolete function and other API-component names:
    ```markdown
    This information is provided as a `table` input artifact that points to the `table_set` output artifact of the `train_run` job that you ran in the previous step.
    ```
2. "Reviewing the Run Output" in Step 3 — I changed
    ```markdown
    The artifacts are stored as HTML files in your project's artifacts directory, under **/User/getting-started-tutorial/jobs/plots/**.
    ```
    to the following to replace the obsolete and platform-specific artifacts path; I'm not sure if the "jobs/plots" at the end is still right:
    ```markdown
    The artifacts are stored as HTML files in your project's artifacts directory, under **&lt;project artifacts path&gt;/jobs/plots/**.
    ```
3. "Running a Model-Testing Job" in Step 4 (which I renamed from "Running a Model-Testing Task") — I replaced the reference to "`train` task" with a reference to "`train_run` job".

**Comment by Sharon-iguazio** [comment]
Currently the Dockeriezed CI tests failed, but I'm not sure whether it's related to my changes (I can't deduce anything from the logs).

**Pull request merged**
