### PR TITLE
[Azure DataStore] Handle storage options as secrets

### PR DESCRIPTION
**Pull request by hayesgb**
This add the ability to pass standard dictionary keys from fsspec's storage_options parameter into mlrun.run.get_dataitem() as secrets.

Enabling this will more easily allow users engaging in exploratory analysis to leverage the mlrun api to fetch data_items from Azure by enabling the following

```
storage_options={'account_name': "<NAME>", 'credential': <CREDENTIAL>}
df = mlrun.run.get_dataitem("az://CONTAINER/myfile.parquet", secrets=storage_options).as_df()
```

### CODE REVIEW

**Review by Hedingber — APPROVED** [review]
@hayesgb Looks good to me, just note you have some conflict

**Comment by hayesgb** [comment]
Fixed merge conflict.  Thanks!

**Comment by Hedingber** [comment]
@hayesgb I now noticed that the test file you added is almost an exact duplicate of `test_azure_blob.py`
I feel like we can merge them without too much effort
Looks like you'll need to make the `verify_auth...` method to behave a bit different whether it's env vars or storage options (can be determined by whether one of the params starts with `AZURE_`)
And in the tests simply always pass storage options to secrets, just in the case of env vars, it will be `None`
WDYT ?

**Comment by hayesgb** [comment]
@Hedingber -- I considered combining the tests, but was concerned about the interpretability.  The two approaches serve entirely different use-cases, and I was worried that if the tests were blended (storing secrets or retrieving environmental variables vs user-passed credentials, which will most likely be done during exploratory analysis) it would lead to confusion and create potential maintainability issues.

**Comment by Hedingber** [comment]
@hayesgb I see your point but I feel like leaving the tests duplicated will hurt maintainability more 😬 , @theSaarco  WDYT ?

**Comment by hayesgb** [comment]
@Hedingber -- No worries.  I consolidated the tests into a single file and updated the PR.  LMKWYT.

**Review by Hedingber — APPROVED** [review]

**Comment by Hedingber** [comment]
@hayesgb Looks great! 
merged
Big appreciation for the detailed comment in the test fixture 👏 👏

**Pull request merged**
