### PR TITLE
Parse function documentation

### PR DESCRIPTION
**Pull request by tebeka**

### CODE REVIEW

**Comment by tebeka** [comment]
Fixes #16

**Comment by tebeka** [comment]
Added defaults here, once this is merge will add outputs in #57

**Comment by yaronha** [comment]
@tebeka how does it integrate with the current code, e.g. when using `code_to_function()` the doc part should be added to the returned function object

**Comment by tebeka** [comment]
I didn't think it should be integrated with current code - will be used by web interface. Will look at it

**Comment by tebeka** [comment]
@yaronha I don't understand how my code should be integrated in `code_to_function`

**Comment by yaronha** [comment]
@tebeka you can see: https://github.com/mlrun/mlrun/blob/80b2805654fd1895e141b35e8740c07b0eb01ae1/mlrun/run.py#L329

`code` is the notebook or file py code, and `r.` is the function object, essentially you should take the `code`, do your magic, and update `r.spec.entry_points` 

see `Entrypoint` struct def in (feel free to edit):
https://github.com/mlrun/mlrun/blob/80b2805654fd1895e141b35e8740c07b0eb01ae1/mlrun/runtimes/base.py#L52

**Comment by yaronha** [comment]
@tebeka can u use `FunctionEntrypoint` class vs dict (see above)

**Comment by yaronha** [comment]
@tebeka are you mapping it to `FunctionEntrypoint` objects? (see above)

**Comment by yaronha** [comment]
@tebeka can u merge w latest

**Pull request merged**
