### PR TITLE
[Projects] Query db for name only when listing projects with `name_only` format

### PR DESCRIPTION
**Pull request by TomerShor**
When listing all projects, the API first loads all projects from the DB, extracts their names, filters them against OPA, and then loads the filtered projects again and returns them.

Instead of loading the entire project objects for all objects, in case the given format is `name_only` - the first query to the DB will return just the `name` column for every project.
This will reduce the number of loaded project in every request.

CAVEAT: In case the requesting user has permissions for every project in the system, listing projects will still be a heavy request and will possibly cause issues.

Fixes https://jira.iguazeng.com/browse/ML-3823

### CODE REVIEW

**Review by theSaarco — COMMENTED** [review]
Suggest fixing the fix a bit...

**Review by Tankilevitch — APPROVED** [review]
LGTM

**Review by Tankilevitch — APPROVED** [review]
LGTM

**Review by theSaarco — APPROVED** [review]
LGTM

**Review by theSaarco — APPROVED** [review]
LGTM

**Review by liranbg — APPROVED** [review]

**Comment by liranbg** [comment]
backport to 1.3.x @TomerShor

**Pull request merged**
